FROM node:20 as build
WORKDIR /usr/src/app
COPY package*.json .
RUN npm install
COPY . .
RUN npm run build

FROM node:20 as production
WORKDIR /usr/src/app
COPY package*.json .
RUN npm install --omit=dev
COPY --from=build /usr/src/app/dist ./dist
COPY --from=build /usr/src/app/node_modules ./node_modules
COPY .env .
COPY /prisma ./prisma
RUN npx prisma generate
CMD [ "npm", "run", "start:prod" ]